### ISSUE TITLE
Demo failed to work

### ISSUE THREAD

**Issue by SkyYap** [another-ai/chat-gpt-powered-nextra#1]
Entered [demo](https://embedbase-nextra-docs-template.vercel.app/) and click on the search bar. 

Tried enter `What is Nextra?` and `How do I get started with Nextra?` and both response get `I don't know.`

**Comment by louis030195** [comment]
@SkyYap Sorry about that, this UI is not intended to be used and was not indexed in embedbase

you can try the example here https://docs.embedbase.xyz/ which is open source
https://github.com/different-ai/embedbase-docs

**Comment by SkyYap** [comment]
@louis030195 Thanks for your explanation. Will shift to embedbase to try.
