### ISSUE TITLE
Unable to edit 

### ISSUE THREAD

**Issue by SkyYap** [another-ai/chat-gpt-powered-nextra#2]
![Untitled1](https://user-images.githubusercontent.com/32660903/228598744-89bdaab1-63ec-4c16-9de9-44b7668eeb22.png)

Attached is the place where I can't find the code base for editing. Search the whole file and still unable to find the code for editing. Anyone can point some light for me?

**Comment by louis030195** [comment]
@SkyYap hey you can check Nextra doc for this https://nextra.site/docs/docs-theme/page-configuration
It's the framework we use here for documentation

**Comment by SkyYap** [comment]
Ya. I am checking the Nextra doc.
